export default function() {
    return {
        character_name: 'Keir',
        class_level: 'Cleric 1',
        background: 'Acolyte',
        player_name: 'Mitch',
        race: 'Dwarf',
        alignment: 'Chaotic Email',
        experience_points: '9001',
        strength: '18',
        dexterity: '18',
        constitution: '18',
        wisdom: '18',
        intelligence: '18',
        charisma: '18',
        proficency_bonus: '20',
        str_Save: false,
        dex_save: false,
        con_save: true,
        wis_save: false,
        int_save: false,
        cha_save: true,
        acrobatics: false,
        animal_handling: false,
        arcana: false,
        athletics: true,
        deception: true,
        history: false,
        insight: true,
        intimidation: false,
        investigation: false,
        medicine: false,
        nature: false,
        perception: false,
        performance: false,
        persuasion: true,
        religion: false,
        slight_of_hand: false,
        stealth: false,
        survival: false,
        armor_class: '30',
        initiative: '+10',
        speed: '50',
        hit_max: '150',
        hit_cur: '77',
        temp_hit: '0',
        hit_dice: '10d8',
        hit_dice_used: '2',
        personality: "i'm a swave mother fucker",
        ideals: "I like to save people",
        bonds: "i'm tied to my family and friends",
        flaws: "Gambling and hookers",
        weapon_one: 'Warhammer',
        wone_bonus: '+7',
        wone_damage: '1d8 + 5',
        weapon_two: '',
        wtwo_bonus: '',
        wtwo_damage: '',
        weapon_three: '',
        wthree_bonus: '',
        wthree_damage: '',
        attacks_spellcasting: '',
        other_prof: 'Common, Dwarvish, Elvish, Celestial',
        feats_traits: 'Two Weapon Fighting',
        equipment: 'Plate MAil',
        cp: '10',
        sp: '5',
        ep: '2',
        pp: '50',
        gp: '5000',

    }
}